global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'psychoneuroassessment'
    static_configs:
      - targets:
        - 'auth-service:80'
        - 'test-service:80'
        - 'donation-service:80'
        - 'analysis-service:80'
        - 'api-gateway:80'